runtime: python38 

instance_class: F1 

env_variables:
  MYSQL_USER: <fill username>
  MYSQL_PASSWORD: <fill password>
  MYSQL_DB: 'todo'
  MYSQL_HOST: <fill mysql gcp ip>

handlers:

- url: /script
  static_dir: static/script

- url: /styles
  static_dir: static/styles
